apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: stateful-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ae07177/mysql_centos7:v3
#        command: ["/bin/sh", "-ec", "while :; do /bin/sh  /tmp/master-slave-logic.sh > /tmp/mysql_setup.log 2>&1 ;  echo '.'; sleep 5 ; done"]
        command: ["/bin/sh", "-ec", "/bin/sh  /tmp/master-slave-logic.sh > /tmp/mysql_setup.log 2>&1 ;   sleep 5 ;while :; do echo . > /dev/null ; done"]
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /data
        - name: master-slave-logic
          subPath: master-slave-logic.sh
          mountPath: /tmp/master-slave-logic.sh
        - name: db-setup
          subPath: configure_db.sh
          mountPath: /tmp/configure_db.sh
      volumes:
        - name: master-slave-logic
          configMap:
            name: master-slave-logic
        - name: db-setup
          configMap:
            name: db-setup
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
