apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdb2-kub2
spec:
  capacity:
    storage: 1500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /stateful/fd298520-b5e2-4755-9162-8eed2861452e
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub2.arvind.com
