apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdb2-kub3
spec:
  capacity:
    storage: 1500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /stateful-vol/4edd29ec-21df-428a-9283-716e9508f49c
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub3.arvind.com
