apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdb1-kub2
spec:
  capacity:
    storage: 1500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /stateful/b556e676-1ffd-4ac8-8d2a-946ef2637e35
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub2.arvind.com
