apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdb1-kub3
spec:
  capacity:
    storage: 1500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /stateful-vol/799280c0-6d7e-4346-b27c-fa49c22a8016
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub3.arvind.com
