kind: PersistentVolume
apiVersion: v1
metadata:
  name: pers-vol
  labels:
    name: pers-vol
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: pers-vol
    fsType: ext4
    readOnly: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pers-vol-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pers-vol
