---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: python
    tier: front
  name: flaskapp
  namespace: diva
spec:
  selector:
    app: flaskapp
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  type: NodePort
